import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/lib/theme-toggle";
import SessionProvider from "@/lib/auth/SessionProvider";
import { Toaster } from "@/components/ui/sonner";
const inter = Tajawal({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}
export default async function RootLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  const ar = lang === "ar";
  return (
    <html dir={ar ? "rtl" : "ltr"} suppressHydrationWarning lang="en">
      <body className={`${inter.variable}  antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <Header />
            {children}
            <Toaster />
            <Footer lang={lang} />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
